const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const admin = fs.readFileSync(path.resolve(__dirname, '../admin/index.html'), 'utf8');

assert.match(admin, /id="caExportPdf">Create weekly update</, 'Cohort Analytics opens a weekly update builder');
assert.match(admin, /id="caReportDialog"/, 'weekly update has a preview dialog');
assert.match(admin, /Week 1 of 3/);
assert.match(admin, /id="caReportMilestone"/);
assert.match(admin, /id="caReportPreparedFor"/);
assert.match(admin, /id="caReportNames"/);
assert.match(admin, /id="caReportIncludeMp"/);
assert.match(admin, /id="caReportIncludeFocused"/);
assert.match(admin, /id="caReportIncludeMethods"/);
assert.match(admin, /id="caReportActionOwner"/, 'weekly actions have an explicit owner');
assert.match(admin, /function caReportScheduledItems/);
assert.match(admin, /phaseLabel=\/\^phase\\s\*\\d\+\$\/i[\s\S]*'Phase '\+\(phaseIndex\+1\)/, 'internal phase keys render as reader-facing Phase 1 labels');
assert.match(admin, /function caReportModel/);
assert.match(admin, /scheduled\.every\(\(item\) => caReportItemDone\(member,item\)\)/, 'on-pace status uses every activity through the selected milestone');
assert.match(admin, /const VIDEO_COMPLETION_PERCENT = 80/, 'video completion uses the configured 80 percent threshold');
assert.doesNotMatch(admin.match(/function eiVideoSummary\(items\)[\s\S]*?\n    \}/)?.[0] || '', />= 90/, 'video summaries do not retain the old 90 percent threshold');
assert.match(admin, /No videos were assigned for this reporting milestone/, 'unassigned weeks do not display a misleading zero');
assert.match(admin, /Videos were assigned, but no Vimeo playback was recorded/, 'assigned videos distinguish no starts from no assignment');
assert.match(admin, /Learners who started/, 'video tables report starts alongside completion');
assert.match(admin, /Total focused time:/);
assert.match(admin, /average per enrolled learner/);
assert.match(admin, /By phase:/);
assert.match(admin, /Expected phase completion by Week/);
assert.match(admin, /At the current weekly pace/);
assert.match(admin, /Weekly target[\s\S]*Total program[\s\S]*full curriculum/, 'the two completion bases are explained');
assert.match(admin, /Access help needed[\s\S]*Check-in suggested[\s\S]*On schedule[\s\S]*Program complete/, 'support statuses are mutually understandable and priority ordered');
assert.match(admin, /sort\(\(a,b\)=>a\.statusPriority-b\.statusPriority/, 'learners are sorted by support priority');
assert.match(admin, /filter\(\(value\)=>value&&!value\.includes\('@'\)\)/, 'email-shaped display names fall back to a readable name');
assert.match(admin, /function caReportBspList/);
assert.match(admin, /<strong>'\+escapeHtml\(label\)\+':<\/strong>/, 'report bullets use bolded summary phrases ending in colons');
assert.match(admin, /Participated this period/);
assert.match(admin, /What is going well/);
assert.match(admin, /What may need attention/);
assert.match(admin, /Suggested actions this week/);
assert.match(admin, /Vimeo engagement during this reporting period/);
assert.match(admin, /Individual progress and support signals/);
assert.match(admin, /Measured as:/);
assert.match(admin, /What it tells you:/);
assert.match(admin, /Combine with:/);
assert.match(admin, /Engagement measures are support signals\. They are not grades or evidence of employee attention or performance\./);
assert.match(admin, /end\+' - '\+caCurrentCohort[\s\S]*' - Cohort update v'\+version/, 'filename follows the dated cohort update convention');
assert.match(admin, /document\.title=filename;[\s\S]*window\.print\(\)/, 'print-to-PDF uses the report filename');
assert.match(admin, /\.ca-report-sheet:last-child \{ break-after:auto; page-break-after:auto; \}/);
assert.match(admin, /\.ca-report-table thead \{ display:table-header-group; \}/);
assert.doesNotMatch(admin, /\.ca-report-stat \{[^}]*border-top:3px solid #EEA320/, 'metric cards do not use decorative orange top bars');
assert.match(admin, /#caPrintReport \.ca-report-footer \{ break-inside:avoid; page-break-inside:avoid; \}/, 'PDF footer does not bleed across pages');
assert.doesNotMatch(admin, /Video timing currently measures lesson-page engagement because Google Drive/);

assert.match(admin, /id="caParticipantUpdate">Share cohort encouragement</);
assert.match(admin, /id="cpDialog"/);
assert.match(admin, /id="cpVariation"/);
assert.match(admin, /value="focus">Weekly focus · Minimal/);
assert.match(admin, /value="momentum">Momentum update · Recommended/);
assert.match(admin, /value="snapshot">Progress snapshot · More detail/);
assert.match(admin, /Chat preview · 1080 × 1350 image format/);
assert.match(admin, /function cpModel/);
assert.match(admin, /eligibleMetrics\.slice\(0,variation\.limit\)/, 'the selected style limits how many safe signals are shown');
assert.match(admin, /focus:\{value:'focus',limit:0/);
assert.match(admin, /momentum:\{value:'momentum',limit:2/);
assert.match(admin, /snapshot:\{value:'snapshot',limit:3/);
assert.match(admin, /variation\.value==='snapshot'&&!suppressNumbers/, 'cohort milestones appear only in the detailed privacy-safe variation');
assert.match(admin, /ids\.size>=3/, 'shared activity milestones require at least three participants');
assert.match(admin, /members\.length>=8&&activeUids\.size>=4/, 'single participant milestones require a larger active cohort');
assert.match(admin, /A milestone this week/);
assert.match(admin, /\.cp-dialog\[open\] \{ display:flex; flex-direction:column; \}/, 'participant popup is constrained to the viewport');
assert.match(admin, /\.cp-dialog-body > \.ca-report-config,\.cp-preview-shell \{ min-height:0; overflow:auto;/, 'both popup columns scroll independently');
assert.match(admin, /cp-card'\+\(model\.achievement\?' has-achievement':'\'\)/, 'detailed cards use a compact layout so the footer remains visible');
assert.match(admin, /members\.length<5\|\|participationRate<\.4/, 'participant totals are suppressed for small or low-participation cohorts');
assert.match(admin, /value>=3&&maximum<=value\/2/, 'small groups and dominant individual contributions are suppressed');
assert.match(admin, /function cpPrivacyCheck/);
assert.match(admin, /message contains an email address|contains '\+found/, 'privacy check blocks learner details in editable copy');
assert.match(admin, /Progress is private\. No names or individual activity are shown\./);
assert.match(admin, /canvas\.width=1080;canvas\.height=1350/);
assert.match(admin, /function cpDownloadPng/);
assert.match(admin, /function cpDownloadPdf/);
assert.match(admin, /function cpCopyMessage/);
assert.match(admin, /cohort encouragement v'\+copy\.version/);
assert.doesNotMatch(admin.match(/function cpCardMarkup\(\) \{[\s\S]*?\n    \}/)?.[0] || '', /member\.displayName|member\.email|learnerRows/, 'participant card renderer contains no learner identity fields');

console.log('weekly cohort update report contracts passed');
