const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const firebase = fs.readFileSync(path.resolve(__dirname, '../assets/firebase.js'), 'utf8');
const rules = fs.readFileSync(path.resolve(__dirname, '../firestore.rules'), 'utf8');
const aiko = fs.readFileSync(path.resolve(__dirname, '../apps/write-to-aiko/index.html'), 'utf8');
const phase1History = fs.readFileSync(path.resolve(__dirname, '../assets/phase1-writing-history.js'), 'utf8');
const nativeHistory = fs.readFileSync(path.resolve(__dirname, '../assets/native-exercise-history.js'), 'utf8');
const explainAiko = fs.readFileSync(path.resolve(__dirname, '../apps/explain-to-aiko/aiko.js'), 'utf8');
const journey = fs.readFileSync(path.resolve(__dirname, '../member-login/content-config.js'), 'utf8');
const grocery = fs.readFileSync(path.resolve(__dirname, '../apps/grocery-list/index.html'), 'utf8');

assert.match(firebase, /async function saveExerciseDraft/);
assert.match(firebase, /async function saveExerciseSubmission/);
assert.match(firebase, /async function getExerciseWork/);
assert.match(firebase, /Promise\.allSettled/);
assert.match(firebase, /"exercise_submissions", submissionId/);
assert.match(firebase, /getDoc\(doc\(readyDb, "users", user\.uid, "completed_exercises", safeExerciseId\)\)/);
assert.match(rules, /match \/users\/\{userId\}\/exercise_work\/\{exerciseId\}/);
assert.match(rules, /match \/users\/\{userId\}\/exercise_submissions\/\{submissionId\}/);
assert.match(aiko, /Continue your draft/);
assert.doesNotMatch(aiko, /View last submission/);
assert.match(aiko, /Previous submissions/);
assert.match(aiko, /saveDraftSoon\(\)/);
assert.match(aiko, /getExerciseWork\('write-to-aiko'\)/);
assert.match(aiko, /design-preview.*write-to-aiko-return/s);
assert.match(phase1History, /No saved work yet/);
assert.match(phase1History, /Draft in progress/);
assert.match(phase1History, /Your most recent work/);
assert.match(phase1History, /Viewing a previous submission/);
assert.match(phase1History, /submit\.disabled=reviewOnly/);
assert.match(phase1History, /\.layout>aside\{position:sticky/);
assert.match(phase1History, /getExerciseWork\(appId\)/);
assert.match(phase1History, /UTLReviewWritingSubmission/);
assert.match(phase1History, /UTLBeginWritingAttempt/);
assert.match(phase1History, /Return to unfinished draft/);
assert.match(phase1History, /Use this response for a new attempt/);
assert.match(phase1History, /\[data-resume\],\.phase1-work-actions \[data-new\],\.phase1-work-actions \[data-edit\]\{background:var\(--navy/);
assert.doesNotMatch(phase1History, /View latest submission/);
assert.match(phase1History, /select\.hidden=!saved\.length/);
assert.match(phase1History, /Viewing submission \$\{viewingIndex\+1\} of \$\{saved\.length\}/);
assert.match(phase1History, /max-width:900px/);
assert.match(phase1History, /hasUsableResponse/);
assert.match(phase1History, /messy-notes-ashley/);
assert.match(phase1History, /saveExerciseDraft/);
assert.match(phase1History, /remoteDraft/);
for (const app of ['messy-notes', 'chalkboard-notes', 'rushed-voice-memo']) {
  const source = fs.readFileSync(path.resolve(__dirname, `../apps/${app}/index.html`), 'utf8');
  assert.match(source, /phase1-writing-history\.js/);
  assert.match(source, /No submitted attempts yet/);
  assert.match(source, /clearAttemptsBtn\.hidden = !attempts\.length/);
  assert.match(source, /Previous submission.*Review its feedback/);
  assert.match(source, /window\.UTLBeginWritingAttempt/);
}
assert.match(nativeHistory, /Draft in progress/);
assert.match(nativeHistory, /Viewing a previous submission/);
assert.match(nativeHistory, /Use this response for a new attempt/);
assert.match(nativeHistory, /\[data-resume\],\.native-work-actions \[data-new\],\.native-work-actions \[data-edit\]\{background:var\(--navy/);
assert.doesNotMatch(nativeHistory, /View latest submission/);
assert.match(nativeHistory, /select\.hidden=!history\.length/);
assert.match(nativeHistory, /if\(reviewingId\)select\.value=reviewingId/);
assert.match(nativeHistory, /max-width:900px/);
assert.match(nativeHistory, /getExerciseWork\(config\.id\)/);
assert.match(nativeHistory, /utl:activity-completed/);
for (const app of ['advisory-board', 'grocery-list-ai', 'rushed-voice-memo-ai']) {
  const source = fs.readFileSync(path.resolve(__dirname, `../apps/${app}/index.html`), 'utf8');
  assert.match(source, /native-exercise-history\.js/);
}
assert.match(explainAiko, /renderSavedWorkHome/);
assert.doesNotMatch(explainAiko, /View latest submission/);
assert.match(explainAiko, /Previous submission/);
assert.match(explainAiko, /Start a new attempt/);
assert.doesNotMatch(journey, /Review original speech|Practice another explanation &rarr;|Resume practice &rarr;/);
assert.match(explainAiko, /Previous submissions/);
assert.match(explainAiko, /id="aikoSavedSelect"/);
assert.match(explainAiko, /Choose a previous submission/);
assert.match(aiko, /id="writeToAikoHistoryList" aria-label="Choose a previous submission"/);
assert.match(aiko, /write-to-aiko-return-tools/);
assert.match(aiko, /Review sample answer →/);
assert.match(aiko, /historyListEl\.addEventListener\('change'/);
assert.match(explainAiko, /saveResultHistory/);
assert.match(explainAiko, /saveExerciseDraft\(APP_ID, APP_TITLE, draftPayload\)/);
assert.match(explainAiko, /Your submitted explanation/);
assert.match(explainAiko, /'explain-to-aiko-120s'/);
assert.match(explainAiko, /hydrateSavedResults\(\);/);
assert.match(grocery, /data-grocery-attempt/);
assert.match(grocery, /viewGroceryAttempt/);
assert.match(grocery, /record \}/);
assert.match(grocery, /renderGrocerySavedWork/);
assert.match(grocery, /Choose a previous submission/);
assert.match(grocery, /id="grocerySubmissionSelect"/);
assert.match(grocery, /viewGroceryAttempt\(displayedHistory\[index\]\)/);
assert.match(grocery, /state\.placements\[`bucket\$\{index \+ 1\}`\]/);
assert.match(grocery, /item\?\.name \|\| item\?\.text/);
assert.match(grocery, /Item details unavailable/);
assert.match(grocery, /saveExerciseSubmission/);
assert.match(grocery, /getExerciseWork\('p1-e1'\)/);
assert.match(grocery, /Optional reflection/);
assert.match(grocery, /id="sampleBtn"[^>]*>Review sample answer<\/button>\s*<button id="checkBtn" class="primary"[^>]*>Submit<\/button>/);
assert.match(grocery, /\.buttons #checkBtn[\s\S]*background: var\(--gold\)/);
assert.match(grocery, /does not affect your score/);
assert.match(grocery, /Start a new attempt/);
assert.match(grocery, /reviewing-grocery-results/);
assert.doesNotMatch(grocery, /Generate new list/);
assert.doesNotMatch(grocery, /id="resetBtn"/);
console.log('exercise work recovery and submission history contracts passed');
