const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const app = read('apps/tsa-diagnostic/index.html');
const content = read('member-login/content-config.js');
const admin = read('admin/index.html');
const fn = read('functions-aiko/index.js');

assert.match(app, /const FORMS=\{\s*A:/, 'Form A should exist');
assert.match(app, /\},\s*B:\{organize:/, 'Form B should exist');
assert.match(app, /\},\s*C:\{organize:/, 'Form C should exist');
assert.match(app, /Part 1a of 3 · Think/);
assert.match(app, /Part 3 of 3 · Act/);
assert.match(app, /utl_tsa_unified_'\+kind\+'_v2/);
assert.match(app, /utl_result_tsa_'\+kind\+'_v2/);
assert.match(app, /navigator\.mediaDevices\.getUserMedia/);
assert.match(app, /window\.SpeechRecognition\|\|window\.webkitSpeechRecognition/);
assert.match(app, /microphone is optional/i);
assert.match(app, /Recording is unavailable[\s\S]*type your response and finish normally/);
assert.match(app, /setTimeout\(\(\)=>controller\.abort\(\),8000\)/, 'AI scoring must have a short timeout');
assert.match(app, /think:\s*Math\.round\(\(organize\+spot\)/);
assert.match(app, /if\(!hasRecommendation\)total=Math\.min\(10,total\)/, 'Copied context without a recommendation must receive a low Speak score');
assert.match(app, /if\(!hasDecision\)total=Math\.min\(8,total\)/, 'Copied context without a decision must receive a low Act score');
assert.match(app, /best:2[\s\S]*best:1[\s\S]*best:0/, 'Act answer position should be balanced across forms');
assert.match(app, /chosenLabel===correctLabel/, 'Organize scoring should follow labels rather than fixed bucket order');
assert.equal((app.match(/\{id:'f[123]-\d+'/g) || []).length, 45, 'Part 2 should have a 45-question bank');
for (const format of [1, 2, 3]) assert.equal((app.match(new RegExp(`format:${format},`, 'g')) || []).length, 15, `format ${format} should have fifteen questions`);
assert.match(app, /function spotAssessmentQuestions\(\)/, 'Part 2 should draw questions at runtime rather than use fixed per-form assignments');
assert.match(app, /state\.spot\.questionIds=picked/, 'The drawn question set should be stored with the attempt so it does not reshuffle on reload');
assert.match(app, /Question \$\{i\+1\} of \$\{questions\.length\}/, 'Part 2 should show one of fifteen questions at a time');
assert.match(app, /Diagnose the grouping.*Complete the grouping.*Build the headings/, 'Part 1b should identify and mix its three question types');
assert.match(app, /spot:spotQuizVisible/, 'Part 2 should use the visible question flow');
assert.match(app, /Answer selected\. You can change it or continue\./, 'Question selection should have clear confirmation');
assert.match(app, /state\.spot\.answers\[q\.id\]===q\.answer\?20\/15:0/, 'Part 2 scoring should award proportional points across all fifteen drawn questions');
assert.match(app, /class="sort-workspace"/, 'Part 1 should use the source-and-buckets grocery-list layout');
assert.match(app, /Every question has exactly one correct answer/, 'Part 1b should explain its deterministic format');
assert.match(app, /Use microphone/, 'Recording mode should be described as a response method rather than the recording action');
assert.match(app, /<h1>Give a clear recommendation<\/h1>/, 'Part 2 should separate the task from the scenario title');
assert.match(app, /<strong>Your task<\/strong>Recommend one option/, 'Part 2 should state the response task explicitly');
assert.match(app, /\.place,\.card,\.label-select\{font-family:Lato,Arial,sans-serif;font-size:14px\}/, 'Placement controls should share one interface font size');
assert.match(app, /label\.textContent='Your TSA profile'/, 'Learners should not see internal form letters in their result heading');
assert.doesNotMatch(app, />Record my answer</, 'The response-mode selector must not look like the recording trigger');
assert.match(app, /<strong>\$\{esc\(x\[0\]\)\}:<\/strong>/, 'Scenario bullets should use bolded summary phrases ending with a colon');
assert.doesNotMatch(app, /\.scenario\{[^}]*border-top:/, 'Routine scenario cards should not use decorative top rails');
assert.doesNotMatch(app, /filler\(t\).*total/, 'Transcript filler counts must not affect the official score');
assert.match(app, /Live transcription is not supported in this browser/);
assert.match(app, /addEventListener\('pagehide'/);
assert.match(app, /saveUserProgress\('tsa-'\+kind\+'-v2'/);
assert.match(app, /attemptId:state\.attemptId/);
assert.match(app, /responses:\{organize:state\.organize,spot:state\.spot,speak:state\.speak,act:state\.act\}/);
assert.match(app, /state\.syncStatus='pending'/, 'Central saving should have a visible pending state');
assert.match(app, /state\.syncStatus='saved'/, 'Central saving should confirm success');
assert.match(app, /state\.syncStatus='failed'/, 'Central saving should retain a retryable failure state');
assert.match(app, /addEventListener\('online'/, 'A failed central save should retry when connectivity returns');
assert.match(app, /function validAi\(value\)/);
assert.match(app, /\$\{esc\(moves\[weakest\]\)\}/);
assert.match(app, /awardAssessment\(\{assessmentId:kind/);

assert.doesNotMatch(content, /tsaDiagnostic/, 'The retired v1/v2 toggle key should no longer exist');
assert.match(content, /diagnosticHref = '\.\.\/apps\/tsa-diagnostic\/index\.html'/, 'The diagnostic should always resolve to the sole assessment');
assert.match(content, /checkpointHref = '\.\.\/apps\/tsa-diagnostic\/index\.html\?assessment=checkpoint'/, 'The checkpoint should route to the sole assessment via the assessment query param');
assert.match(content, /Before the program/, 'the diagnostic card should identify when to take it');
assert.match(content, /same assessment and scoring with a different scenario set/, 'the checkpoint card should explain that it is the same assessment implementation');
assert.doesNotMatch(content, /ws-phase-number">C<\/div>/, 'The admin-only preview card should be removed now that there is only one version');
assert.doesNotMatch(content, /adminUnifiedPreview/, 'The retired admin-preview variable should no longer exist');
assert.doesNotMatch(admin, /data-aiko-version-card="tsaDiagnostic"/, 'The retired v1/v2 toggle card should no longer exist');
assert.doesNotMatch(admin, /<strong>Unified assessment<\/strong>/);
assert.match(admin, /form=A&reset=1[^]*Diagnostic — Everyday decisions/, 'Admin should still be able to preview each scenario set');
assert.match(admin, /form=B&reset=1[^]*Diagnostic — Planning under pressure/);
assert.match(admin, /form=C&reset=1[^]*Diagnostic — Community choices/);
assert.match(admin, /assessment=checkpoint&preview=1&form=C&reset=1/);
assert.match(fn, /exports\.scoreTsaDiagnostic = onRequest/);
assert.match(fn, /Do not rescore it\. Add concise, evidence-based comments only/);
assert.doesNotMatch(fn, /speakScore: bounded|actScore: bounded/, 'AI must not alter the official score');
assert.match(fn, /No relevant content found/);
assert.match(fn, /fallback: true/);

console.log('unified TSA diagnostic resilience, scoring, routing, and admin contracts passed');
