const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const app = read('apps/tsa-diagnostic-v2/index.html');
const content = read('member-login/content-config.js');
const admin = read('admin/index.html');
const fn = read('functions-aiko/index.js');

assert.match(app, /const FORMS=\{\s*A:/, 'Form A should exist');
assert.match(app, /\},\s*B:\{organize:/, 'Form B should exist');
assert.match(app, /\},\s*C:\{organize:/, 'Form C should exist');
assert.match(app, /Challenge 1 of 4 · Think/);
assert.match(app, /Challenge 4 of 4 · Act/);
assert.match(app, /utl_tsa_unified_'\+kind\+'_v2/);
assert.match(app, /utl_result_tsa_'\+kind\+'_v2/);
assert.match(app, /navigator\.mediaDevices\.getUserMedia/);
assert.match(app, /window\.SpeechRecognition\|\|window\.webkitSpeechRecognition/);
assert.match(app, /microphone is optional/i);
assert.match(app, /Recording is unavailable[\s\S]*type your response and finish normally/);
assert.match(app, /setTimeout\(\(\)=>controller\.abort\(\),8000\)/, 'AI scoring must have a short timeout');
assert.match(app, /think:\s*Math\.round\(\(organize\+spot\)/);
assert.match(app, /if\(!hasRecommendation\)total=Math\.min\(10,total\)/, 'Copied context without a recommendation must receive a low Speak score');
assert.match(app, /if\(!hasDecision\)total=Math\.min\(8,total\)/, 'Copied context without a decision must receive a low Act score');
assert.match(app, /best:2[\s\S]*best:1[\s\S]*best:0/, 'Act answer position should be balanced across forms');
assert.match(app, /chosenLabel===correctLabel/, 'Organize scoring should follow labels rather than fixed bucket order');
assert.equal((app.match(/\{id:'[oglmr]\d+'/g) || []).length, 56, 'Challenge 2 should have a 56-question bank');
assert.equal((app.match(/type:'overlap'/g) || []).length, 20, 'Part 1 should have 20 overlap questions');
for (const type of ['gap','level','misplaced','revision']) assert.equal((app.match(new RegExp(`type:'${type}'`, 'g')) || []).length, 9, `${type} should have nine calibrated questions`);
assert.match(app, /const PART1_ASSIGNMENTS=\{diagnostic:/, 'Part 1 should use explicit five-question forms');
assert.match(app, /const QUIZ_ASSIGNMENTS=\{diagnostic:/, 'The quiz should use explicit calibrated forms');
assert.match(app, /state\.spot\[idsKey\]=\[\.\.\.assigned\]/, 'The exact question set should be stored with the attempt');
assert.match(app, /state\.spot\[ordersKey\]\[id\]=order/, 'Rendered option order should be stored for audit and resume');
assert.match(app, /Question \$\{i\+1\} of \$\{questions\.length\}/, 'Part 2 should show one of ten questions at a time');
assert.match(app, /spot:spotQuizVisible/, 'Challenge 2 should use the visible two-part flow');
assert.match(app, /Part 1 · 5 overlap questions/, 'Challenge 2 should explain Part 1');
assert.match(app, /Part 2 · 10 structure questions/, 'Challenge 2 should explain Part 2');
assert.match(app, /Example 1 · Same idea:/, 'Part 1 should begin with a positive worked example');
assert.match(app, /Example 2 · Related, but not overlapping:/, 'Part 1 should distinguish related ideas from duplicates');
assert.match(app, /None of the above.*always available/, 'Part 2 should explain its none option');
assert.match(app, /Answer selected\. You can change it or continue\./, 'Question selection should have clear confirmation');
assert.match(app, /state\.spot\.part1Answers\[q\.id\]===q\.answer\?1:0/, 'Part 1 should score five questions at one point each');
assert.match(app, /state\.spot\.answers\[q\.id\]===q\.answer\?1\.5:0/, 'Part 2 scoring should be deterministic and weighted toward structure');
assert.match(app, /class="sort-workspace"/, 'Challenge 1 should use the source-and-buckets grocery-list layout');
assert.match(app, /Select the full pair:/, 'Challenge 2 duplicate instructions should explain both selections');
assert.match(app, /Each question has one intended answer/, 'Challenge 2 should explain its deterministic format');
assert.match(app, /Use microphone/, 'Recording mode should be described as a response method rather than the recording action');
assert.match(app, /\.place,\.card,\.label-select\{font-family:Lato,Arial,sans-serif;font-size:14px\}/, 'Placement controls should share one interface font size');
assert.match(app, /label\.textContent='Your TSA profile'/, 'Learners should not see internal form letters in their result heading');
assert.doesNotMatch(app, />Record my answer</, 'The response-mode selector must not look like the recording trigger');
assert.match(app, /<strong>\$\{esc\(x\[0\]\)\}:<\/strong>/, 'Scenario bullets should use bolded summary phrases ending with a colon');
assert.doesNotMatch(app, /\.scenario\{[^}]*border-top:/, 'Routine scenario cards should not use decorative top rails');
assert.doesNotMatch(app, /filler\(t\).*total/, 'Transcript filler counts must not affect the official score');
assert.match(app, /Live transcription is not supported in this browser/);
assert.match(app, /addEventListener\('pagehide'/);
assert.match(app, /saveUserProgress\('tsa-'\+kind\+'-v2'/);
assert.match(app, /attemptId:state\.attemptId/);
assert.match(app, /responses:\{organize:state\.organize,spot:state\.spot,speak:state\.speak,act:state\.act\}/);
assert.match(app, /state\.syncStatus='pending'/, 'Central saving should have a visible pending state');
assert.match(app, /state\.syncStatus='saved'/, 'Central saving should confirm success');
assert.match(app, /state\.syncStatus='failed'/, 'Central saving should retain a retryable failure state');
assert.match(app, /addEventListener\('online'/, 'A failed central save should retry when connectivity returns');
assert.match(app, /function validAi\(value\)/);
assert.match(app, /\$\{esc\(moves\[weakest\]\)\}/);
assert.match(app, /awardAssessment\(\{assessmentId:kind/);

assert.match(content, /tsaDiagnostic:\s*"utl_tsa_diagnostic_version"/);
assert.match(content, /tsa-diagnostic-v2\/index\.html/);
assert.match(content, /assessment=checkpoint/);
assert.match(content, /ws-phase-number">C<\/div>/, 'Admins should see Assessment C in the member workspace');
assert.match(content, /Try Assessment C &rarr;/);
assert.match(content, /adminUnifiedPreview = isAdminUser\(\)/, 'Assessment C must remain an admin-only preview');
assert.match(admin, /data-aiko-version-card="tsaDiagnostic"/);
assert.match(admin, /<strong>Unified assessment<\/strong>/);
assert.match(admin, /form=A&amp;reset=1[^]*Everyday decisions/);
assert.match(admin, /form=B&amp;reset=1[^]*Planning under pressure/);
assert.match(admin, /form=C&amp;reset=1[^]*Community choices/);
assert.match(admin, /assessment=checkpoint&amp;preview=1&amp;form=C&amp;reset=1/);
assert.match(fn, /exports\.scoreTsaDiagnostic = onRequest/);
assert.match(fn, /Do not rescore it\. Add concise, evidence-based comments only/);
assert.doesNotMatch(fn, /speakScore: bounded|actScore: bounded/, 'AI must not alter the official score');
assert.match(fn, /No relevant content found/);
assert.match(fn, /fallback: true/);

console.log('unified TSA diagnostic resilience, scoring, routing, and admin contracts passed');
