const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const app = read('apps/tsa-diagnostic/index.html');
const content = read('member-login/content-config.js');
const admin = read('admin/index.html');
const fn = read('functions-aiko/index.js');
const firebase = read('assets/firebase.js');
const rules = read('firestore.rules');

assert.match(app, /const FORMS=\{\s*A:/, 'Form A should exist');
assert.match(app, /\},\s*B:\{organize:/, 'Form B should exist');
assert.match(app, /\},\s*C:\{organize:/, 'Form C should exist');
assert.match(app, /Part 1a of 3 · Think/);
assert.match(app, /Part 3 of 3 · Act/);
assert.match(app, /utl_tsa_unified_'\+kind\+'_v2/);
assert.match(app, /utl_result_tsa_'\+kind\+'_v2/);
assert.match(app, /navigator\.mediaDevices\.getUserMedia/);
assert.match(app, /window\.SpeechRecognition\|\|window\.webkitSpeechRecognition/);
assert.match(app, /microphone is optional/i);
assert.match(app, /Recording is unavailable[\s\S]*type your response and finish normally/);
assert.match(app, /setTimeout\(\(\)=>controller\.abort\(\),8000\)/, 'AI scoring must have a short timeout');
assert.match(app, /think:\s*Math\.round\(\(organize\+spot\)/);
assert.match(app, /if\(!hasRecommendation\)total=Math\.min\(10,total\)/, 'Copied context without a recommendation must receive a low Speak score');
assert.match(app, /if\(!hasDecision\)total=Math\.min\(8,total\)/, 'Copied context without a decision must receive a low Act score');
assert.match(app, /best:2[\s\S]*best:1[\s\S]*best:0/, 'Act answer position should be balanced across forms');
assert.match(app, /chosenLabel===correctLabel/, 'Organize scoring should follow labels rather than fixed bucket order');
assert.equal((app.match(/Organize the nine tasks according to when they should be handled/g) || []).length, 3, 'Every Part 1a form should state the timing-based organizing rule');
assert.match(app, /Reserve the train tickets before prices rise/);
assert.match(app, /Pack pens and identification the night before/);
assert.match(app, /Buy matching storage boxes after measuring the rooms and settling in/);
assert.doesNotMatch(app, /Measure the rooms, then buy matching storage boxes later/, 'Part 1a items should not combine actions with different timing classifications');
assert.equal((app.match(/\{id:'f[123]-\d+'/g) || []).length, 45, 'Part 2 should have a 45-question bank');
for (const format of [1, 2, 3]) assert.equal((app.match(new RegExp(`format:${format},`, 'g')) || []).length, 15, `format ${format} should have fifteen questions`);
assert.match(app, /function spotAssessmentQuestions\(\)/, 'Part 2 should draw questions at runtime rather than use fixed per-form assignments');
assert.match(app, /state\.spot\.questionIds=picked/, 'The drawn question set should be stored with the attempt so it does not reshuffle on reload');
assert.match(app, /Question \$\{i\+1\} of \$\{questions\.length\}/, 'Part 2 should show one of fifteen questions at a time');
assert.match(app, /Spot what doesn’t belong.*Extend the structure.*Select the best overall structure/, 'Part 1b should identify and mix its three question types');
assert.match(app, /spot:spotQuizVisible/, 'Part 2 should use the visible question flow');
assert.match(app, /Answer selected\. You can change it or continue\./, 'Question selection should have clear confirmation');
assert.match(app, /state\.spot\.answers\[q\.id\]===q\.answer\?20\/15:0/, 'Part 2 scoring should award proportional points across all fifteen drawn questions');
assert.match(app, /class="sort-workspace"/, 'Part 1 should use the source-and-buckets grocery-list layout');
assert.match(app, /Every question has exactly one correct answer/, 'Part 1b should explain its deterministic format');
assert.match(app, /Use microphone/, 'Recording mode should be described as a response method rather than the recording action');
assert.match(app, /<h1>Give a clear recommendation<\/h1>/, 'Part 2 should separate the task from the scenario title');
assert.match(app, /<strong>Your task<\/strong>Recommend one option/, 'Part 2 should state the response task explicitly');
assert.match(app, /keywords:\[\['library','park','community hall','hall'\]/, 'Part 2 venue scoring should accept every available recommendation');
assert.match(app, /let decides=\(d\.choice!==null\?3:0\)\+\(hasDecision\?4:0\)/, 'Part 3 Decides should require action selection and explicit commitment');
assert.doesNotMatch(app, /t\.match\(\/\[\.!\?\]\//, 'speech-to-text punctuation must not contribute to scoring');
assert.match(app, /leads\+supports\+focuses/, 'Speak should use the C3 dimensions');
assert.match(app, /decides\+adapts\+advances/, 'Act should use the C3 dimensions');
assert.match(app, /\.place,\.card,\.label-select\{font-family:Lato,Arial,sans-serif;font-size:14px\}/, 'Placement controls should share one interface font size');
assert.match(app, /label\.textContent='Your TSA profile'/, 'Learners should not see internal form letters in their result heading');
assert.doesNotMatch(app, />Record my answer</, 'The response-mode selector must not look like the recording trigger');
assert.match(app, /<strong>\$\{esc\(x\[0\]\)\}:<\/strong>/, 'Scenario bullets should use bolded summary phrases ending with a colon');
assert.doesNotMatch(app, /\.scenario\{[^}]*border-top:/, 'Routine scenario cards should not use decorative top rails');
assert.doesNotMatch(app, /filler\(t\).*total/, 'Transcript filler counts must not affect the official score');
assert.match(app, /Live transcription is not supported in this browser/);
assert.match(app, /addEventListener\('pagehide'/);
assert.match(app, /saveUserProgress\('tsa-'\+kind\+'-v2'/);
assert.match(app, /attemptId:state\.attemptId/);
assert.match(app, /responses:\{organize:state\.organize,spot:state\.spot,speak:state\.speak,act:state\.act\}/);
assert.match(app, /state\.syncStatus='pending'/, 'Central saving should have a visible pending state');
assert.match(app, /state\.syncStatus='saved'/, 'Central saving should confirm success');
assert.match(app, /state\.syncStatus='failed'/, 'Central saving should retain a retryable failure state');
assert.match(app, /addEventListener\('online'/, 'A failed central save should retry when connectivity returns');
assert.match(app, /function validAiSection\(value,type\)/, 'GenAI section scores must be validated independently');
assert.match(app, /\$\{esc\(moves\[weakest\]\)\}/);
assert.match(app, /awardAssessment\(\{assessmentId:kind/);
assert.match(app, /const SPOT_BANK_RELEASE='[^']+'/ , 'the question bank should have a release identifier');
assert.match(app, /function spotQuestionVersion\(id\)/, 'question versions should be tracked independently');
assert.match(app, /responseTimeMs:/, 'item response time should be recorded');
assert.match(app, /answerChanges:/, 'answer changes should be recorded');
assert.match(app, /Report a problem with this question/, 'learners should have a subtle optional item-quality report');
assert.match(app, /More than one answer seems correct/, 'quality feedback should capture ambiguous answers');
assert.match(app, /None of the answers seems correct/, 'quality feedback should capture missing correct answers');
assert.match(app, /saveAssessmentItemAttempt\(assessmentItemPayload\(score\)\)/, 'completed assessments should save item telemetry');
assert.match(firebase, /async function saveAssessmentItemAttempt/, 'Firebase should expose item-attempt persistence');
assert.match(rules, /match \/assessment_item_attempts\/\{attemptId\}/, 'Firestore should protect item telemetry');
assert.match(rules, /match \/assessment_item_reviews\/\{questionId\}/, 'Firestore should protect admin review history');

assert.doesNotMatch(content, /tsaDiagnostic/, 'The retired v1/v2 toggle key should no longer exist');
assert.match(content, /diagnosticHref = '\.\.\/apps\/tsa-diagnostic\/index\.html'/, 'The diagnostic should always resolve to the sole assessment');
assert.match(content, /checkpointHref = '\.\.\/apps\/tsa-diagnostic\/index\.html\?assessment=checkpoint'/, 'The checkpoint should route to the sole assessment via the assessment query param');
assert.match(content, /Before the program/, 'the diagnostic card should identify when to take it');
assert.match(content, /same assessment and scoring with a different scenario set/, 'the checkpoint card should explain that it is the same assessment implementation');
assert.doesNotMatch(content, /ws-phase-number">C<\/div>/, 'The admin-only preview card should be removed now that there is only one version');
assert.doesNotMatch(content, /adminUnifiedPreview/, 'The retired admin-preview variable should no longer exist');
assert.doesNotMatch(admin, /data-aiko-version-card="tsaDiagnostic"/, 'The retired v1/v2 toggle card should no longer exist');
assert.doesNotMatch(admin, /<strong>Unified assessment<\/strong>/);
assert.match(admin, /form=A&reset=1[^]*Diagnostic — Everyday decisions/, 'Admin should still be able to preview each scenario set');
assert.match(admin, /form=B&reset=1[^]*Diagnostic — Planning under pressure/);
assert.match(admin, /form=C&reset=1[^]*Diagnostic — Community choices/);
assert.match(admin, /assessment=checkpoint&preview=1&form=C&reset=1/);
assert.match(admin, /No option is keyed or preferred/, 'Admin guidance should explain that Part 2 accepts supported alternatives');
assert.match(admin, /Every listed action is treated equally/, 'Admin guidance should explain Part 3 choice-neutral scoring');
assert.match(admin, /id="tsaSpeakGenAi"/, 'Speak should have its own GenAI scoring toggle');
assert.match(admin, /id="tsaActGenAi"/, 'Act should have its own GenAI scoring toggle');
assert.match(app, /saveTsaScoringComparison/, 'enabled GenAI scoring should log private deterministic comparisons');
assert.match(firebase, /return \{ speakGenAiEnabled: false, actGenAiEnabled: false \}/, 'both GenAI scorers should default off');
assert.match(firebase, /tsa_scoring_comparisons/, 'private scoring comparisons should be persisted');
assert.match(rules, /match \/tsa_scoring_comparisons\/\{attemptId\}/, 'Firestore should protect scoring-comparison logs');
assert.match(app, /settings\.speakGenAiEnabled\|\|settings\.actGenAiEnabled/, 'GenAI should only be called when at least one section is enabled');
assert.doesNotMatch(app, /AI comments were unavailable/, 'GenAI fallback should be invisible to learners');
assert.match(admin, /contentPreview=part1b/, 'Admin Content Data should link to the all-question learner preview');
assert.match(admin, /contentPreview=part1a/, 'Admin Content Data should provide form-specific Part 1a previews');
assert.match(admin, /contentPreview=part2/, 'Admin Content Data should provide form-specific Part 2 previews');
assert.match(admin, /contentPreview=part3/, 'Admin Content Data should provide form-specific Part 3 previews');
assert.match(app, /state\.spot\.questionIds=SPOT_QUESTION_BANK\.map/, 'Part 1b preview should show the full 45-question bank');
assert.match(app, /Admin preview · responses are not saved/, 'learner-view previews must not write assessment progress');
assert.match(fn, /exports\.scoreTsaDiagnostic = onRequest/);
assert.match(fn, /Speak rubric when enabled: Leads 0–8, Supports 0–14, Focuses 0–8/);
assert.match(fn, /Act rubric when enabled: Decides 0–10, Adapts 0–12, Advances 0–8/);
assert.match(fn, /No relevant content found/);
assert.match(fn, /fallback: true/);

console.log('unified TSA diagnostic resilience, scoring, routing, and admin contracts passed');
