const assert = require('node:assert/strict');
const fs = require('node:fs');

const rewardUi = fs.readFileSync('assets/reward-ui.js', 'utf8');
const appHeader = fs.readFileSync('assets/app-reward-header.js', 'utf8');
const workspace = fs.readFileSync('member-login/content-config.js', 'utf8');
const messyNotes = fs.readFileSync('apps/messy-notes/index.html', 'utf8');
const scqa = fs.readFileSync('apps/scqa-builder/index.html', 'utf8');
const styles = fs.readFileSync('styles.css', 'utf8');
const tactileButtons = fs.readFileSync('assets/tactile-buttons.js', 'utf8');

assert(rewardUi.includes('data-award-stage="takeaway"'), 'exercise completion includes a takeaway stage');
assert(rewardUi.includes('Go to next exercise'), 'exercise completion leads learners directly to the next exercise');
assert(rewardUi.includes('nextExerciseHref(phaseProgress.phase)'), 'the next-exercise action returns to the correct phase');
assert(!rewardUi.includes("content:'DONE'"), 'exercise completion does not display a DONE watermark');
assert(rewardUi.includes('opacity:.22'), 'completion background texture remains subtle');
assert(rewardUi.includes('html,body{max-width:100%;overflow-x:clip}'), 'reward popovers cannot create horizontal page overflow');
assert(rewardUi.includes('Phase '), 'exercise completion reports phase progress');
assert(rewardUi.includes('activities in today’s mission'), 'exercise completion reports daily mission progress when set');
assert(appHeader.includes('makeAttemptsCollapsible'), 'shared exercise UI collapses previous attempts');
assert(appHeader.includes('overflow-x:clip'), 'shared exercise UI guards against horizontal overflow');
assert(styles.includes('overflow-x: clip'), 'public pages guard against horizontal overflow');
assert(workspace.includes('program’s Day '), 'workspace explains the learner’s program pace');
assert(workspace.includes('Intern, Analyst, Associate, Principal, and Executive'), 'workspace explains the five levels');
assert(workspace.includes('Your first day at MA'), 'Phase 1 avoids repeating the orientation welcome headline');
assert(workspace.includes('ws-phase-practice-cta'), 'Phase 1 presents practice navigation as one clear button');
assert(!workspace.includes('<a class="ws-ai-link-card"'), 'AI practice uses one clear action instead of a redundant link bar');
assert(workspace.includes('(!seen && !orientationDone)'), 'completed onboarding does not reopen the introductory journey card');
assert(workspace.includes('journeyCard.classList.add("ws-complete")'), 'completed introductory content receives a subdued state');
assert(workspace.includes('orientationCard.classList.add("ws-complete")'), 'completed orientation receives a subdued state');
assert(workspace.includes('return complete ? false : defaultOpen'), 'completed practice cards stay collapsed');
assert(workspace.includes('practiceOpenState(cardId, enabled && isNext, done)'), 'the next available exercise opens automatically');
assert(messyNotes.includes('contextViewTab'), 'messy notes can switch between source note and context');
assert(scqa.includes('secondScqaModal'), 'SCQA confirms the learner will take a different angle');
assert(scqa.includes('secondScqaAcknowledged: false'), 'SCQA confirmation begins unacknowledged');
assert(scqa.includes('if (state.secondScqaAcknowledged) goToScreen(3)'), 'SCQA confirmation only interrupts the first transition');
assert(scqa.includes('state.secondScqaAcknowledged = true'), 'SCQA saves the learner’s acknowledgement');
assert(scqa.includes('.form-header p { width: 100%; max-width: none;'), 'SCQA instructions use the available content width');
assert(!scqa.includes('How to make this one different'), 'SCQA avoids repeating the second-formulation guidance');
const appHtml = fs.readdirSync('apps').filter((name) => fs.existsSync(`apps/${name}/index.html`)).map((name) => fs.readFileSync(`apps/${name}/index.html`, 'utf8')).join('\n');
const shadowTokens = [...appHtml.matchAll(/--(?:eisenhower-|lsh-|slo-|bad-news-)?shadow:\s*([^;]+);/g)];
assert(shadowTokens.every((match) => match[1].trim() === 'none'), 'standalone exercise card-shadow tokens are disabled');
assert(!tactileButtons.includes('box-shadow:0 5px 0'), 'buttons no longer use decorative offset shadows');
assert(!rewardUi.includes('12px 12px 0 rgba(238,163,32,.18)'), 'exercise awards do not use a decorative offset shadow');
assert(workspace.includes('.ws-practice-card{box-shadow:none}'), 'workspace cards use borders instead of decorative elevation');

console.log('weekly audit completion, pacing, overflow, and exercise UX contracts passed');
