const assert = require('node:assert/strict');
const fs = require('node:fs');

const rewardUi = fs.readFileSync('assets/reward-ui.js', 'utf8');
const appHeader = fs.readFileSync('assets/app-reward-header.js', 'utf8');
const workspace = fs.readFileSync('member-login/content-config.js', 'utf8');
const messyNotes = fs.readFileSync('apps/messy-notes/index.html', 'utf8');
const scqa = fs.readFileSync('apps/scqa-builder/index.html', 'utf8');
const styles = fs.readFileSync('styles.css', 'utf8');
const tactileButtons = fs.readFileSync('assets/tactile-buttons.js', 'utf8');

assert(!rewardUi.includes('data-award-stage="takeaway"'), 'exercise completion does not repeat the reflection in a third popup stage');
assert(rewardUi.includes('Save and return to Learning Journey'), 'exercise completion returns learners to the canonical course map');
assert(rewardUi.includes('nextExerciseHref(appId, phaseProgress.phase)'), 'the completion action preserves the current phase and completed exercise');
assert(rewardUi.includes('&completed=" + encodeURIComponent(appId || "exercise")'), 'the Learning Journey can acknowledge the activity just completed');
assert(!rewardUi.includes("content:'DONE'"), 'exercise completion does not display a DONE watermark');
assert(rewardUi.includes('opacity:.22'), 'completion background texture remains subtle');
assert(rewardUi.includes('html,body{max-width:100%;overflow-x:clip}'), 'reward popovers cannot create horizontal page overflow');
assert(rewardUi.includes('Phase '), 'exercise completion reports phase progress');
assert(rewardUi.includes('activities in today’s mission'), 'exercise completion reports daily mission progress when set');
assert(appHeader.includes('makeAttemptsCollapsible'), 'shared exercise UI collapses previous attempts');
assert(appHeader.includes('normalizeLearningJourneyLinks'), 'shared exercise UI repairs stale phase-return links at runtime');
assert(appHeader.includes('".utility-cluster"') && appHeader.includes('header.insertBefore(engagement, timer || null)'), 'shared exercise headers place Level and MP before every timer variant');
assert(!appHeader.includes('enhanceTextareas'), 'shared exercise UI leaves response fields free of Markdown formatting controls');
assert(appHeader.includes('overflow-x:clip'), 'shared exercise UI guards against horizontal overflow');
assert(styles.includes('overflow-x: clip'), 'public pages guard against horizontal overflow');
assert(workspace.includes('Continue where you left off'), 'workspace gives the learner one clear next action');
assert(workspace.includes('Learning Journey'), 'workspace uses the learning journey as its navigation anchor');
assert(workspace.includes('data-journey-module-toggle'), 'learning phases expand without leaving the journey');
assert(workspace.includes('data-journey-preview'), 'every learning activity provides an explanatory preview');
assert(workspace.includes('ws-journey-phase-tabs'), 'the compact journey switches between phases with accessible tabs');
assert(workspace.includes('role="tabpanel"'), 'each phase tab controls one activity panel');
assert(workspace.includes('ws-journey-sequence'), 'journey activities carry phase-based sequence numbers');
assert(workspace.includes('ws-journey-type-video') && workspace.includes('ws-journey-type-exercise'), 'videos and exercises have distinct visual treatments');
assert(workspace.includes('data-journey-preview-scrim'), 'activity previews use a focused drawer or mobile sheet');
assert(workspace.includes('.ws-journey-activity-locked{opacity:1}'), 'locked-row styling does not dim or obscure its preview drawer');
assert(!workspace.includes('Context and instructions'), 'exercise previews do not promise a context step that may not exist');
assert(workspace.includes('Review the exercise brief and source material'), 'exercise previews describe the source-first flow used by exercises such as messy notes');
assert(workspace.includes('completed > 0 ? "In progress"'), 'partially completed phase tabs use meaningful progress language');
assert(workspace.includes('Completed') && workspace.includes('Up next') && workspace.includes('Locked'), 'journey activity states use clear language');
assert(workspace.includes('focusedLessonPrototypeHtml'), 'Rule of three has a focused lesson-player prototype');
assert(workspace.includes('getPhase(phaseKey).lessons.find(function (lesson) { return lesson.id === requestedLesson; })'), 'every Learning Journey lesson opens in the focused lesson player');
assert(workspace.includes('Return to Learning Journey'), 'the focused lesson returns to the canonical course map');
assert(workspace.includes('get("phase")'), 'return links can restore the selected Learning Journey phase');
assert(workspace.includes('focusedLessonNavHtml'), 'focused lessons keep their Learning Journey return link in the sticky header');
assert(workspace.includes('window.location.replace(learningJourneyHref(phaseKey))'), 'legacy phase overview routes return to the canonical Learning Journey');
assert(workspace.includes('owningPhase && owningPhase !== phaseKey'), 'lesson links opened from the wrong phase route are repaired');
assert(workspace.includes('"?lesson=" + encodeURIComponent(lesson.id) + "#lessons"'), 'daily mission videos open the focused lesson rather than a retired phase overview');
assert(workspace.includes('ws-video-help-toggle'), 'video troubleshooting includes a visible expand and collapse control');
assert(workspace.includes('.ws-video-access-help[open] .ws-video-help-toggle:before'), 'the troubleshooting control changes from plus to minus when expanded');
assert(workspace.includes('Intern, Analyst, Associate, Principal, and Executive'), 'workspace explains the five levels');
assert(workspace.includes('Your first day at MA'), 'Phase 1 avoids repeating the orientation welcome headline');
assert(workspace.includes('ws-phase-practice-cta'), 'Phase 1 presents practice navigation as one clear button');
assert(!workspace.includes('<a class="ws-ai-link-card"'), 'AI practice uses one clear action instead of a redundant link bar');
assert(workspace.includes('(!seen && !orientationDone)'), 'completed onboarding does not reopen the introductory journey card');
assert(workspace.includes('journeyCard.classList.add("ws-complete")'), 'completed introductory content receives a subdued state');
assert(workspace.includes('orientationCard.classList.add("ws-complete")'), 'completed orientation receives a subdued state');
assert(messyNotes.includes('contextViewTab'), 'messy notes can switch between source note and context');
assert(messyNotes.includes('Watch the setup') && messyNotes.includes('Complete the exercise'), 'messy notes prototypes an explicit context-to-exercise flow');
assert(messyNotes.includes('utl_context_p1_e3_seen'), 'messy notes remembers when the learner has completed the setup step');
assert(messyNotes.includes('utl_context_complete_p1-e3'), 'messy notes uses the canonical workspace context-completion key');
assert(messyNotes.includes("eventId: CONTEXT_REWARD_ID") && messyNotes.includes("type: 'context-completed'"), 'messy notes awards the standard context-completion event');
assert(messyNotes.includes('Mark setup complete and continue · +5 MP'), 'messy notes makes context completion and the next step explicit');
assert(messyNotes.includes('index.html?phase=phase1#learning-journey'), 'messy notes returns to the selected Learning Journey phase');
assert(messyNotes.includes('Open it in Google Drive'), 'messy notes provides a fallback when the embedded context video cannot open');
const contextFlow = fs.readFileSync('assets/exercise-context-flow.js', 'utf8');
assert(contextFlow.includes('"grocery-list"') && contextFlow.includes('"speak-like-obama"'), 'the shared setup-first flow covers exercises across all three phases');
assert(contextFlow.includes('"utl_context_complete_" + config[0]'), 'shared exercise setup uses canonical context-completion keys');
assert(contextFlow.includes('eventId: "context:" + config[0]'), 'shared exercise setup uses the standard one-time context reward');
assert(contextFlow.includes('reviewButton.textContent = "Review setup"'), 'completed exercises keep setup visibly available for review');
assert(workspace.includes('"setup=1"'), 'Learning Journey exercise links open the setup step for preview and review');
assert(scqa.includes('reframeLever: null'), 'SCQA reframe begins with no lever chosen');
assert(scqa.includes('complication:') && scqa.includes('question:') && scqa.includes('answer:'), 'SCQA offers the three reframe levers named in its own intro copy');
assert(scqa.includes('function chooseLever(lever)'), 'SCQA lets the learner commit to one reframe lever instead of writing a second full SCQA blind');
assert(!scqa.includes('secondScqaModal'), 'SCQA no longer interrupts the learner with a blocking confirmation modal');
assert(scqa.includes('.form-header p { width: 100%; max-width: none;'), 'SCQA instructions use the available content width');
assert(!scqa.includes('How to make this one different'), 'SCQA avoids repeating the second-formulation guidance');
const appHtml = fs.readdirSync('apps').filter((name) => fs.existsSync(`apps/${name}/index.html`)).map((name) => fs.readFileSync(`apps/${name}/index.html`, 'utf8')).join('\n');
assert(!appHtml.includes('app-reward-header.js?v=20260729-phase3-4'), 'exercise pages do not retain the stale shared-header cache key');
  assert(appHtml.includes('app-reward-header.js?v=20260730-celebration-1'), 'exercise pages load the current compact responsive reward header');
assert(!/member-login\/phase-[123]/.test(appHtml), 'exercise navigation no longer returns learners to deprecated phase pages');
assert(!/Back to Phase [123] exercises/.test(appHtml), 'exercise headers consistently return learners to the Learning Journey');
assert(appHtml.includes('member-login/index.html#learning-journey'), 'exercise navigation links directly to the Learning Journey');
const shadowTokens = [...appHtml.matchAll(/--(?:eisenhower-|lsh-|slo-|bad-news-)?shadow:\s*([^;]+);/g)];
assert(shadowTokens.every((match) => match[1].trim() === 'none'), 'standalone exercise card-shadow tokens are disabled');
assert(!tactileButtons.includes('box-shadow:0 5px 0'), 'buttons no longer use decorative offset shadows');
assert(!rewardUi.includes('12px 12px 0 rgba(238,163,32,.18)'), 'exercise awards do not use a decorative offset shadow');
assert(workspace.includes('.ws-practice-card{box-shadow:none}'), 'workspace cards use borders instead of decorative elevation');

console.log('weekly audit completion, pacing, overflow, and exercise UX contracts passed');
